# Generated by Django 5.2.8 on 2025-11-18 03:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0002_procuct_cartitem'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Procuct',
            new_name='Product',
        ),
    ]
